INSERT INTO categories (name) VALUES
    ('The X-Files'),
    ('Sex Education'),
    ('The Crown'),
    ('Theater Life'),
    ('Photoshoots'),
    ('Charity & Public'),
    ('Candid Moments'),
    ('Fan Art Tributes'),
    ('Interviews'),
    ('Public Appearances'),
    ('Behind The Scenes')
ON CONFLICT (name) DO NOTHING;

INSERT INTO videos (id, title, category_id, duration, youtube_id, subtitles, sort_order) VALUES
    ('media-bts', 'WIRED Autocomplete Interview with Gillian Anderson', (SELECT id FROM categories WHERE name='Interviews'), '11:42', 'u66sTWpxswM', ARRAY['Does Gillian Anderson have a British accent? Yes, I am bidialectal!','I grew up in both London and Grand Rapids, Michigan.','Is Dana Scully a real medical doctor? Yes, in the series she absolutely is.','How did I prepare for Margaret Thatcher in The Crown? Listening to her voice on repeat.','Thank you for these wonderful questions! This was WIRED Autocomplete.'], 1),
    ('video-kimmel', 'Gillian Anderson on Jimmy Kimmel Live', (SELECT id FROM categories WHERE name='Public Appearances'), '08:15', 'ezypNGtH6Cw', ARRAY['Welcome back to the show. We are here with the incredible Gillian Anderson!','I hear your new Netflix series ''Scoop'' is causing quite a stir in the UK.','Yes, it''s about the famous Prince Andrew BBC Newsnight interview.','I play Emily Maitlis, who was the main journalist conducting the interview.','It was high stakes, high tension, and a very intense transformation.'], 2),
    ('video-fallon', 'Gillian Anderson on The Tonight Show starring Jimmy Fallon', (SELECT id FROM categories WHERE name='Public Appearances'), '07:54', '7AvRuvPaumw', ARRAY['My next guest is an Emmy and Golden Globe-winning actress!','Jimmy, it''s so wonderful to be back in New York.','We have some classic photos of you here from the X-Files days.','Oh my goodness, look at that hair! I remember that red wig so vividly.','Sex Education is also finishing its run. It''s been an absolute joy to play Jean.'], 3),
    ('video-colbert', 'Gillian Anderson on Stephen Colbert: Transforming into Thatcher', (SELECT id FROM categories WHERE name='The Crown'), '09:30', '9WwTqrxncxY', ARRAY['Let''s talk about the hair. The Thatcher hair is iconic.','It took about two hours every single day to get that helmet of hair perfect.','And the voice! How did you lower your voice to match her tone?','It''s about breathing from the chest and finding that very deliberate rhythm.','She was a controversial figure, but playing her was a fascinating challenge.'], 4),
    ('video-sexed-trailer', 'Sex Education Season 4 Official Netflix Trailer', (SELECT id FROM categories WHERE name='Sex Education'), '02:44', 'TJjMJmYLMWs', ARRAY['Welcome to Cavendish Sixth Form College, our brand new start.','Jean Milburn is back and dealing with a brand new baby!','I am a licensed therapist, Otis, I know how relationships work.','An intimate look at the final, emotional season of the hit show.','Stream the final season now, only on Netflix.'], 5),
    ('video-thatcher-comp', 'Margaret Thatcher''s Most Intense Scenes in The Crown', (SELECT id FROM categories WHERE name='The Crown'), '06:12', 'VvvC8wpuo2k', ARRAY['Your Majesty, I think we understand each other perfectly.','I have no intention of changing my cabinet or my direction.','The working class must learn the value of hard work and self-reliance.','A battle of wills between the Queen and the Iron Prime Minister.','Gillian Anderson''s powerhouse performance that won her the Emmy.'], 6),
    ('video-xfiles-trailer', 'The X-Files Pilot Episode Classic Remastered Trailer', (SELECT id FROM categories WHERE name='The X-Files'), '02:10', 'RXDWfUbLE-E', ARRAY['My name is Fox Mulder. I believe in things they want us to forget.','I''m Dana Scully, I''ve been assigned to write a scientific analysis of your work.','A series of unexplained deaths in the woods of Oregon.','Do you believe in extraterrestrial intelligence, Agent Scully?','The truth is out there. Trust no one.'], 7),
    ('video-sayes-charity', 'SAYes Youth Mentoring Campaign Introduction', (SELECT id FROM categories WHERE name='Charity & Public'), '05:15', '_UnefqDLgwg', ARRAY['Mentoring is about showing up and providing a stable, loving presence.','For kids in residential care, turning 18 is a terrifying milestone.','SAYes helps them prepare for independent, successful adult lives.','We provide guidance, goal-setting, and emotional support networks.','Please join me in supporting this incredibly important work.'], 8),
    ('video-mirren-conv', 'Gillian Anderson & Dame Helen Mirren: In Conversation', (SELECT id FROM categories WHERE name='Interviews'), '14:50', 'aTTPea6gHh4', ARRAY['Helen, you''ve played queens, detectives, and everything in between.','And Gillian, your career has been incredibly bold and versatile.','We discuss the challenges faced by female leads in theater and television.','You have to learn to say ''no'' to roles that do not feed your soul.','An inspiring masterclass between two legendary British stage icons.'], 9),
    ('video-elle-song', 'Gillian Anderson - Elle Song Association Challenge', (SELECT id FROM categories WHERE name='Public Appearances'), '06:30', 'b1ltnIguJ9Q', ARRAY['Welcome to Elle! Today I have 15 seconds to associate a word with a song.','The first word is ''TRUTH''... Oh, ''I Want to Believe'' isn''t a song, is it?','How about ''I Will Survive''? Yes, that works!','This is highly stressful but absolutely hilarious.','Thanks for watching! Go stream Sex Education on Netflix.'], 10);
