INSERT INTO admin_events (id, title, event_type, description, day, month, event_time, location, capacity, registered) VALUES
  ('ev-seed-001', 'Gillian Welch Masterclass', 'Workshop', 'An intimate masterclass exploring Gillian''s vocal and fingerpicking techniques.', '02', 'August', '2:00 PM EST', 'Nashville, TN', 50, '0'),
  ('ev-seed-002', 'Storytellers Session: Gillian & Dave', 'Panel', 'Gillian and Dave Rawlings sit down to share the stories behind their most beloved songs.', '08', 'August', '7:30 PM EST', 'Ryman Auditorium', 200, '0'),
  ('ev-seed-003', 'Vinyl Night: Time (The Revelator)', 'Listening Party', 'A full-album listening experience of the classic Time (The Revelator) on vinyl.', '14', 'August', '8:00 PM EST', 'The Basement East', 80, '0'),
  ('ev-seed-004', 'Charity Dinner Gala', 'Fundraiser', 'An exclusive evening of fine dining and live music to benefit music education programs.', '22', 'August', '6:00 PM EST', 'Belle Meade, TN', 120, '0'),
  ('ev-seed-005', 'Behind the Lyrics: Songwriting Deep Dive', 'Workshop', 'A deep dive into the craft of songwriting with Gillian and special guests.', '05', 'September', '3:00 PM EST', 'Bluebird Cafe', 60, '0'),
  ('ev-seed-006', 'Gillian Welch & Friends: Night of Duets', 'Concert', 'A one-night-only celebration of duets featuring Gillian and surprise musical guests.', '12', 'September', '8:00 PM EST', 'Brooklyn Steel', 300, '0'),
  ('ev-seed-007', 'Exclusive Fan Q&A', 'Meet & Greet', 'An exclusive virtual Q&A session for fan club members.', '18', 'September', '1:00 PM EST', 'Online (Zoom)', 100, '0'),
  ('ev-seed-008', 'The Bootleg Series Listening Party', 'Listening Party', 'Hear rare outtakes and unreleased tracks from the Bootleg Series archives.', '25', 'September', '7:00 PM EST', 'Third Man Records', 70, '0'),
  ('ev-seed-009', 'Guitar Techniques with Gillian', 'Workshop', 'Learn fingerstyle guitar techniques straight from the source.', '04', 'October', '11:00 AM EST', 'Nashville, TN', 40, '0'),
  ('ev-seed-010', 'Fall Harvest Charity Show', 'Concert', 'A benefit concert supporting local Tennessee food banks.', '11', 'October', '7:00 PM EST', 'The Caverns, TN', 200, '0'),
  ('ev-seed-011', 'Vinyl Signing Event', 'Meet & Greet', 'Meet Gillian and get your vinyl collection signed.', '19', 'October', '4:00 PM EST', 'Grimey''s Records', 50, '0'),
  ('ev-seed-012', 'Songwriter Roundtable', 'Panel', 'An intimate roundtable discussion on the art of storytelling through song.', '26', 'October', '6:30 PM EST', 'Station Inn', 75, '0'),
  ('ev-seed-013', 'Halloween Acoustic Set', 'Concert', 'A spooky evening of acoustic favorites and haunting covers.', '31', 'October', '9:00 PM EST', 'The Blue Room', 100, '0'),
  ('ev-seed-014', 'Podcast Live Recording', 'Panel', 'Be in the audience for a live recording of the Officially Inspired podcast.', '07', 'November', '2:00 PM EST', 'Oberlin, OH', 90, '0'),
  ('ev-seed-015', 'Veterans Day Benefit Concert', 'Fundraiser', 'A tribute concert benefiting veterans'' wellness programs.', '11', 'November', '7:00 PM EST', 'Washington, DC', 250, '0'),
  ('ev-seed-016', 'Soulful Sundays: Intimate Performance', 'Concert', 'An intimate Sunday evening performance in the heart of Los Angeles.', '17', 'November', '6:00 PM EST', 'The Troubadour, LA', 150, '0'),
  ('ev-seed-017', 'Thanksgiving Food Drive Meetup', 'Community', 'Volunteer alongside fellow fans to support the Nashville Food Bank.', '23', 'November', '10:00 AM EST', 'Nashville Food Bank', 60, '0'),
  ('ev-seed-018', 'Bootleg Vinyl Vol. 2 Premiere', 'Listening Party', 'Exclusive first listen of the Bootleg Vinyl Volume 2 collection.', '29', 'November', '8:00 PM EST', 'Easy Eye Sound', 80, '0'),
  ('ev-seed-019', 'Holiday Acoustic Matinee', 'Concert', 'A family-friendly afternoon of holiday classics and acoustic warmth.', '06', 'December', '3:00 PM EST', 'The Fox Theatre, Atlanta', 350, '0'),
  ('ev-seed-020', 'Members-Only Holiday Party', 'Community', 'An exclusive holiday gathering for fan club members with live music and refreshments.', '13', 'December', '7:00 PM EST', 'Nashville, TN', 100, '0'),
  ('ev-seed-021', 'Year-End Fan Appreciation Show', 'Concert', 'A special thank you concert celebrating another incredible year together.', '20', 'December', '8:00 PM EST', 'The Ryman Auditorium', 400, '0'),
  ('ev-seed-022', 'New Year''s Eve Countdown Show', 'Concert', 'Ring in the new year with live music and a champagne toast.', '31', 'December', '9:00 PM EST', 'Nashville, TN', 300, '0'),
  ('ev-seed-023', 'January Residency Night 1', 'Concert', 'Night one of an intimate two-night residency at City Winery.', '10', 'January', '8:00 PM EST', 'City Winery, NYC', 120, '0'),
  ('ev-seed-024', 'January Residency Night 2', 'Concert', 'Night two of an intimate two-night residency at City Winery.', '11', 'January', '8:00 PM EST', 'City Winery, NYC', 120, '0'),
  ('ev-seed-025', 'Songwriting Workshop: Crafting Choruses', 'Workshop', 'A focused workshop on writing memorable, powerful choruses.', '18', 'January', '2:00 PM EST', 'Nashville, TN', 40, '0'),
  ('ev-seed-026', 'Intimate House Concert', 'Concert', 'A rare house concert experience in a private Franklin residence.', '25', 'January', '7:00 PM EST', 'Franklin, TN', 30, '0'),
  ('ev-seed-027', 'Folk Alliance International Showcase', 'Concert', 'Gillian represents at the annual Folk Alliance International conference.', '01', 'February', '9:00 PM EST', 'Montreal, Canada', 200, '0'),
  ('ev-seed-028', 'Valentine''s Day Duets Special', 'Concert', 'A romantic evening of duets celebrating love and harmony.', '14', 'February', '8:00 PM EST', 'The Birchmere, VA', 180, '0'),
  ('ev-seed-029', 'Archival Listening: Outtakes & Rarities', 'Listening Party', 'Delve into the archives for a listening session of rare outtakes and demos.', '21', 'February', '7:00 PM EST', 'Nashville, TN', 60, '0'),
  ('ev-seed-030', 'Women in Roots Music Panel', 'Panel', 'A discussion on the contributions of women in roots and Americana music.', '28', 'February', '3:00 PM EST', 'MerleFest, NC', 150, '0'),
  ('ev-seed-031', 'Spring Preview Acoustic Set', 'Concert', 'A preview of new material and spring tour favorites.', '07', 'March', '7:30 PM EST', 'The Georgia Theatre', 250, '0'),
  ('ev-seed-032', 'St. Patrick''s Day Barn Dance', 'Community', 'A Celtic-inspired barn dance with live folk music and community dancing.', '15', 'March', '6:00 PM EST', 'Nashville, TN', 100, '0'),
  ('ev-seed-033', 'Masterclass: Vocal Harmony Techniques', 'Workshop', 'Learn Gillian''s approach to crafting rich, layered vocal harmonies.', '22', 'March', '1:00 PM EST', 'Nashville, TN', 35, '0'),
  ('ev-seed-034', 'South by Southwest Official Showcase', 'Concert', 'Gillian''s official SXSW showcase performance in Austin.', '28', 'March', '11:00 PM EST', 'Austin, TX', 300, '0'),
  ('ev-seed-035', 'Fan Club Meetup & Brunch', 'Community', 'A casual brunch meetup for fan club members to connect in person.', '05', 'April', '11:00 AM EST', 'Nashville, TN', 80, '0');
